<?php 
ini_set('soap.wsdl_cache_enabled',0);
/**
 * Implementatio of hook_init()
 */

function westward_services_init(){
	drupal_add_css(drupal_get_path('module','westward_services').'/css/style.css');
	drupal_add_library('system', 'ui.accordion');
	drupal_add_js(drupal_get_path('module','westward_services').'/js/script.js');
}


/**
 * Implementation of hook_permission()
 */

function westward_services_permission(){
	return array(
	'access annual review' =>array(
		'title' => t('Access annual review'), 
      	'description' => t('Access annual review.'),
	),
	'access annual review listing' =>array(
		'title' => t('Access annual review listing'), 
      	'description' => t('Access annual review listing.'),
	),
	);
}


/**
 * implementation of hook_menu()
 */
function westward_services_menu(){
	$items=array();

	/*$items['annual_review']=array(
	'title'=>t('Annual review'),
	'page callback'=>'westward_services_get_annaul_review',
	'access arguments'=>array('access annual review'),
	'description'=>t('Annual review'),
	'type' => MENU_CALLBACK, 
	);*/
	
	$items['annual_review_listing']=array(
	'title'=>t('Annual review'),
	'page callback'=>'westward_services_get_client_listing',
	'access arguments'=>array('access annual review listing'),	
	'description'=>t('Annual review listing'),
	'type' => MENU_CALLBACK, 
	);
	
	
	$items['annual_review/%']=array(
	'title'=>t('Annual review'),
	'page callback'=>'westward_services_get_annaul_review',
	'page arguments' => array(1),
	'access arguments'=>array(1),
	'access callback'=>'westward_services_access_annual_review',
	'description'=>t('Annual review'),
	'type' => MENU_CALLBACK, 
	);
	
	$items['annual_review_pdf/%']=array(
	'title'=>t('Annual review'),
	'page callback'=>'westward_services_get_annaul_review_pdf',
	'page arguments' => array(1),
	'access arguments'=>array(1),
	'access callback'=>'westward_services_access_annual_review',
	'description'=>t('Annual review'),
	'type' => MENU_CALLBACK, 
	);

	return $items;
	
}


function westward_services_access_annual_review($annual_id){
	global $user;	
	if(in_array('administrator', $user->roles)){
	    return TRUE;
	}else{
		$userobject=user_load($user->uid);  
		if($userobject->uid){
			if(isset($userobject->field_new_associatedaccountid['und'][0]['value'])){
			     $guid= $userobject->field_new_associatedaccountid['und'][0]['value'];
			     $parameters = array(			
					"Username" => "portalcrm",
					"Password" => "txKA0VsiBb",
					"AssociatedAccountID" => $guid,
				    "Status" => "Both",			   
			     );
			     
			     $client = new SoapClient("https://crm.westwardadvisors.com:8443/WestwardCustomData.CustomCRMData.svc?wsdl");
			     if($client){
				     $value= $client->GetAnnualReviewListing($parameters);
	                 $service= $value->GetAnnualReviewListingResult->AnnualReviewListing;
			          if(is_object($service)){							
							if($service->Status='PUBLISHED'){						    	
						    	if($service->AnnualReviewID==$annual_id){
						    		return TRUE;
						    	}
							}
					  }elseif(is_array($service) && count($service)){
							for($i=0;$i<count($service);$i++){
								$row=$i+1;
								if($service[$i]->Status=='PUBLISHED'){
									if($service[$i]->AnnualReviewID==$annual_id){
							    		return TRUE;
							    	}
								}
							}
							
					 }// end of if(is_object($service)){
			     } // end of if($client){
			} // end of if(isset($userobject->field_new_associatedaccountid['und'][0]['value']))
		} // end of if($userobject->uid){
	}
	
	return FALSE;
}

/**
 * implementation of hook_block()
 */

function westward_services_block_info(){
  $blocks['client_annual_review_block'] = array(
    'info' => t('Client Annual Review block'),
   );
  return $blocks;
}

/**
 * Implementation of hook_block_view().
 */
function westward_services_block_view($delta='') {
	  global $user;
	  $block = array();
	  switch ($delta) {
	    case 'client_annual_review_block':
	      $block['subject'] = '';
	      $content=westward_services_get_client_annual_reviews();
	      $block['content'] = $content;
	      break;
	  }
      return $block;
}


function westward_services_get_client_annual_reviews(){
	
	    global $user;
	    
	   $userobject=user_load($user->uid);  

	   //var_dump($userobject);
		
	    $result='';
		if($userobject->uid){
		if(!empty($userobject->field_new_associatedaccountid['und'])){
			$guid= $userobject->field_new_associatedaccountid['und'][0]['value'];
		
			$parameters = array(			
				"Username" => "portalcrm",
				"Password" => "txKA0VsiBb",
				"AssociatedAccountID" => $guid,
			    "Status" => "Both",
			   
			);
			
		   $client = new SoapClient("https://crm.westwardadvisors.com:8443/WestwardCustomData.CustomCRMData.svc?wsdl");
			
		   $value= $client->GetAnnualReviewListing($parameters);
		   
		   //dsm($value);
			
           $service= $value->GetAnnualReviewListingResult->AnnualReviewListing;
            
           $result.='
					<div>
					<ul>';		
			if(is_object($service)){
				$id=$service->AnnualReviewID;
				if($service->Status='PUBLISHED'){
			    	$result.='<li><a href="'.base_path().'annual_review/'.$id.'">'.$service->AnnualReviewName.' | '.$service->AnnualReviewYearEnd.'</a></li>';
				}
		   }elseif(is_array($service) && count ($service)){
				for($i=0;$i<count($service);$i++){
					$row=$i+1;
					if($service[$i]->Status=='PUBLISHED'){
						$id=$service[$i]->AnnualReviewID;
						$result.='<li><a href="'.base_path().'annual_review/'.$id.'">'.$service[$i]->AnnualReviewName.' | '.$service[$i]->AnnualReviewYearEnd.'</a></li>';
					}
				}
			}
			$result.='</ul></div>';
		}
		}
		
		return $result;
		
}





function westward_services_get_annaul_review($guid){	

		$client = new SoapClient("https://crm.westwardadvisors.com:8443/WestwardCustomData.CustomCRMData.svc?wsdl");
		/* testing */
		//$result = $client->GetData();;
		//var_dump( $result);
		
		/*$parameters = array("OrgUriStr" => "http://wcmcrm01/Westward/XRMServices/2011/Organization.svc",
			"Domain" =>  "westward",
			"Username" => "portalcrm",
			"Password" => "txKA0VsiBb",
			"CustomerName" => "john"
		);
		
		$result = $client->GetAccounts( $parameters);
		$accounts = explode(",", $result->GetAccountsResult);
		
		$result= "<h2> Accounts</h2>";
		foreach ($accounts as $value)
		{
			$result.= $value . "<br/>";
		}*/
		
		$parameters = array(			
			"Username" => "portalcrm",
			"Password" => "txKA0VsiBb",
			"AnnualReviewID" => $guid
		);
		
		/*$parameters = array(			
			"Username" => "portalcrm",
			"Password" => "txKA0VsiBb",
			"AnnualReviewID" => $guid
		);	*/	
		
		$value= $client->GetAnnualReview($parameters);
		//dsm($value);
		$result['content']=$value->GetAnnualReviewResult;		
		$result['id']=$guid;	
		return theme('annual_review',array('content'=>$result));
		
		
}

/**
* Implements hook_theme().
*/
function westward_services_theme($existing, $type, $theme, $path)
{
  
   return array(
      'annual_review' => array(
        'variables' => array('content'=>NULL),
        'template' => 'annual_review',
        'path' => drupal_get_path('module', 'westward_services'),
      ),
      'annual_review_pdf' => array(
        'variables' => array('content'=>NULL),
        'template' => 'annual_review_pdf',
        'path' => drupal_get_path('module', 'westward_services'),
      ),
    );
  
}


function westward_services_get_client_listing(){
    // get all clients
	
	/*$query = 'SELECT DISTINCT(ur.uid) 
	  FROM {users_roles} AS ur
	  WHERE ur.rid IN (:rids)';
	$result = db_query($query, array(':rids' => array(5)));
	
	$uids = $result->fetchCol();
	
	$users = user_load_multiple($uids);*/
	
	//$user=user_load(1762);
	$client = new SoapClient("https://crm.westwardadvisors.com:8443/WestwardCustomData.CustomCRMData.svc?wsdl");

	
    
	
	$query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'user')
       ->fieldCondition('field_new_associatedaccountid','value','','!=');
    $results = $query->execute();
   
	foreach($results as $result){
		foreach($result as $value){
			$users[]=$value->uid;
		}
	}
	$userobject=array();
	$result='';
	
	$result.='<div class="annual-listing"><div id="accordion">';
	foreach($users as $user){
		$userobject=user_load($user);
		
		if($userobject->uid){
			$guid= $userobject->field_new_associatedaccountid['und'][0]['value'];
			$parameters = array(			
				"Username" => "portalcrm",
				"Password" => "txKA0VsiBb",
				"AssociatedAccountID" => $guid,
			    "Status" => "Both",
			   
			);
			
		   $value= $client->GetAnnualReviewListing($parameters);
		   
		   //dsm($value);
			
           $service= $value->GetAnnualReviewListingResult->AnnualReviewListing;
            
           $result.='<h3><a href="#">'.$userobject->field_first_name['und'][0]['value'].' '.$userobject->field_last_name['und'][0]['value'].'
						    </a>
					</h3>
					<div>
					<ul>';		
			if(is_object($service)){
				$id=$service->AnnualReviewID;
			    $result.='<li><a href="'.base_path().'annual_review/'.$id.'">'.$service->AnnualReviewName.' | '.$service->AnnualReviewYearEnd.' | '.$service->Status.'</a></li>';
			}elseif(is_array($service) && count ($service)){
				for($i=0;$i<count($service);$i++){
					$row=$i+1;
					$id=$service[$i]->AnnualReviewID;
					$result.='<li><a href="'.base_path().'annual_review/'.$id.'">'.$service[$i]->AnnualReviewName.' | '.$service[$i]->AnnualReviewYearEnd.' | '.$service[$i]->Status.'</a></li>';
				}
			}
			$result.='</ul></div>';
		}
	}
	$result.='</div></div>';
 
    
    return $result;
}

function westward_services_get_annaul_review_pdf($id){
	$client = new SoapClient("https://crm.westwardadvisors.com:8443/WestwardCustomData.CustomCRMData.svc?wsdl");
	$parameters = array(			
			"Username" => "portalcrm",
			"Password" => "txKA0VsiBb",
			"AnnualReviewID" => $id
		);	
	//return 'hai';
	
	$value= $client->GetAnnualReview($parameters);
	
	$result['content']=$value->GetAnnualReviewResult;		
	$result['id']=$id;
	return theme('annual_review_pdf',array('content'=>$result));
    
	
    
    
	
}


function westward_services_money($money){
	$money=floatval($money);
    if($money < 0){
		$money=str_replace('-','',$money);
		$money='('.number_format($money).')';
		$money=trim($money);
	}else{
		$money='<span class="amt">'.number_format($money).'</span>';
	}
	return $money;

}


